language:
  - php
  - c

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

addons:
  apt:
    packages:
      - gdb
      - valgrind

env:
  matrix:
    - CC=gcc
    - CC=clang

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - ./.travis/build debug

script:
  - phpenv config-rm xdebug.ini || true
  - .travis/run-tests valgrind
  - .travis/run-tests

after_failure:
  - .travis/after_failure
