#ifndef TURBOSLIM_INTERFACES_H
#define TURBOSLIM_INTERFACES_H

#include "php_turboslim.h"

extern zend_class_entry* ce_TurboSlim_Interfaces_CallableResolverInterface;
extern zend_class_entry* ce_TurboSlim_Interfaces_CollectionInterface;
extern zend_class_entry* ce_TurboSlim_Interfaces_InvocationStrategyInterface;
extern zend_class_entry* ce_TurboSlim_Interfaces_RouteGroupInterface;
extern zend_class_entry* ce_TurboSlim_Interfaces_RouteInterface;
extern zend_class_entry* ce_TurboSlim_Interfaces_RouterInterface;
extern zend_class_entry* ce_TurboSlim_Interfaces_Http_CookiesInterface;
extern zend_class_entry* ce_TurboSlim_Interfaces_Http_EnvironmentInterface;
extern zend_class_entry* ce_TurboSlim_Interfaces_Http_HeadersInterface;

TURBOSLIM_VISIBILITY_HIDDEN extern const zend_function_entry fe_TurboSlim_Interfaces_CallableResolverInterface[];
TURBOSLIM_VISIBILITY_HIDDEN extern const zend_function_entry fe_TurboSlim_Interfaces_CollectionInterface[];
TURBOSLIM_VISIBILITY_HIDDEN extern const zend_function_entry fe_TurboSlim_Interfaces_InvocationStrategyInterface[];
TURBOSLIM_VISIBILITY_HIDDEN extern const zend_function_entry fe_TurboSlim_Interfaces_RouteGroupInterface[];
TURBOSLIM_VISIBILITY_HIDDEN extern const zend_function_entry fe_TurboSlim_Interfaces_RouteInterface[];
TURBOSLIM_VISIBILITY_HIDDEN extern const zend_function_entry fe_TurboSlim_Interfaces_RouterInterface[];
TURBOSLIM_VISIBILITY_HIDDEN extern const zend_function_entry fe_TurboSlim_Interfaces_Http_CookiesInterface[];
TURBOSLIM_VISIBILITY_HIDDEN extern const zend_function_entry fe_TurboSlim_Interfaces_Http_EnvironmentInterface[];
TURBOSLIM_VISIBILITY_HIDDEN extern const zend_function_entry fe_TurboSlim_Interfaces_Http_HeadersInterface[];

#endif /* TURBOSLIM_INTERFACES_H */
