#!/bin/sh

(
	cd "$(dirname $(readlink -qe $0))/../"
	make install
	if [ "x$1" = "xvalgrind" ]; then
		USE_ZEND_ALLOC=0
		ZEND_DONT_UNLOAD_MODULES=1
		export USE_ZEND_ALLOC
		export ZEND_DONT_UNLOAD_MODULES
		shift
		valgrind --leak-check=full --trace-children=yes --trace-children-skip=/bin/sh --track-origins=yes --num-callers=50 $(phpenv which php) tests/phpunit "$@"
	elif [ "x$1" = "xphp" ]; then
		NO_INTERACTION=1
		TESTS="-q tests/phpt"
		export NO_INTERACTION
		export TESTS
		shift
		make test "$@"
	elif [ "x$1" = "xphpvg" ]; then
		NO_INTERACTION=1
		TESTS="-m -q tests/phpt"
		export NO_INTERACTION
		export TESTS
		shift
		make test "$@"
	else
		ONECOVERAGE=1
		export ONECOVERAGE
		shift
		$(phpenv which php) tests/phpunit "$@"
	fi
)

exit $?
