#ifndef TURBOSLIM_EXCEPTION_METHODNOTALLOWEDEXCEPTION_H
#define TURBOSLIM_EXCEPTION_METHODNOTALLOWEDEXCEPTION_H

#include "php_turboslim.h"

extern zend_class_entry* ce_TurboSlim_Exception_MethodNotAllowedException;

TURBOSLIM_VISIBILITY_HIDDEN extern const zend_function_entry fe_TurboSlim_Exception_MethodNotAllowedException[];

#endif /* TURBOSLIM_EXCEPTION_METHODNOTALLOWEDEXCEPTION_H */
