#ifndef TURBOSLIM_EXCEPTION_CONTAINERVALUENOTFOUNDEXCEPTION_H
#define TURBOSLIM_EXCEPTION_CONTAINERVALUENOTFOUNDEXCEPTION_H

#include "php_turboslim.h"

TURBOSLIM_VISIBILITY_HIDDEN int init_container_value_not_found_exception();

extern zend_class_entry* ce_TurboSlim_Exception_ContainerValueNotFoundException;

#endif /* TURBOSLIM_EXCEPTION_CONTAINERVALUENOTFOUNDEXCEPTION_H */
