#ifndef TURBOSLIM_TRAITS_CALLABLERESOLVERAWARETRAIT_H
#define TURBOSLIM_TRAITS_CALLABLERESOLVERAWARETRAIT_H

#include "php_turboslim.h"

TURBOSLIM_VISIBILITY_HIDDEN extern zend_class_entry* ce_TurboSlim_CallableResolverAwareTrait;
TURBOSLIM_VISIBILITY_HIDDEN PHP_METHOD(TurboSlim_CallableResolverAwareTrait, resolveCallable);
TURBOSLIM_VISIBILITY_HIDDEN TURBOSLIM_ATTR_NONNULL int CallableResolverAwareTrait_resolveCallable(zval* return_value, zval* this_ptr, zval* callable);
TURBOSLIM_VISIBILITY_HIDDEN int init_callable_resolver_aware_trait();

#endif /* TURBOSLIM_TRAITS_CALLABLERESOLVERAWARETRAIT_H */
